sudo: required

language: cpp

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/DiligentGraphics/DiligentCore.git ../DiligentCore --recursive
  - . ../DiligentCore/BuildTools/Scripts/travis/before_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

matrix:
  include:
  - os: linux
    compiler: gcc
    env: CONFIG=Debug
  - os: osx
    compiler: clang
    env:
      - CONFIG=Debug
      - IOS=false
  - os: linux
    compiler: gcc
    env: CONFIG=Release
  - os: osx
    compiler: clang
    env:
      - CONFIG=Release
      - IOS=false

script:

  #- cd ./BuildTools/FormatValidation
  #- . ../../../DiligentCore/BuildTools/Scripts/travis/validate_format.sh
  #- cd ../../..
  - cd ..
  - |
    echo "cmake_minimum_required(VERSION 3.6)" > CMakeLists.txt
    echo "Project(DiligentEngineTest)" >> CMakeLists.txt
   #echo "add_subdirectory(DiligentCore)" >> CMakeLists.txt
    echo "add_subdirectory(DiligentTests)" >> CMakeLists.txt
  - . ./DiligentCore/BuildTools/Scripts/travis/build.sh

after_success:

  #- cd ../build/install
  #- export ZIP_NAME=DiligentTools-${TRAVIS_OS_NAME}-${GLSLANG_BUILD_TYPE}.zip;
  #- zip -r ${ZIP_NAME} .
