image:
- Visual Studio 2019

install:
  # Download the Windows SDK 17763 installer
  #- ps: Invoke-WebRequest -Uri "https://download.microsoft.com/download/6/4/3/643A4705-728F-4D2A-8973-207E59D7713C/winsdksetup.exe" -OutFile "C:\temp\winsdksetup.exe"

  # Run the SDK installer silently to install the desired components
  # Modify the /features option to include only the components you need
  #- cmd: C:\temp\winsdksetup.exe /norestart /features OptionId.DesktopCppx64
  #- ps: |
  #    $url = "https://go.microsoft.com/fwlink/?linkid=2331960"
  #    $out = "C:\Temp\winsdksetup.exe"
  #    New-Item -ItemType Directory -Force -Path C:\Temp | Out-Null
  #    Write-Host "Downloading Windows SDK installer..."
  #    Invoke-WebRequest -Uri $url -OutFile $out
  #    Write-Host "Installing Windows SDK..."
  #    & $out /norestart | Out-Null
  #    if ($LASTEXITCODE -ne 0) { throw "Windows SDK installer failed with exit code $LASTEXITCODE" }

before_build:
  - dir "C:\Program Files (x86)\Windows Kits\10\Include" || exit /b 0
  - dir "C:\Program Files (x86)\Windows Kits\10\Lib" || exit /b 0
  - dir "C:\Program Files (x86)\Windows Kits\10\bin" || exit /b 0

  - dir "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0" || exit /b 0
  - dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0" || exit /b 0
  - dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0" || exit /b 0

  #- dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64" || exit /b 0
  #- dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64" || exit /b 0
  
  #- dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64" || exit /b 0
  #- dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64" || exit /b 0

  - dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64" || exit /b 0
  - dir "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64" || exit /b 0

  #- cmake -S . -B ./build -G "Visual Studio 16 2019" -A x64