name: Linux

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ubuntu -> Build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout Diligent Engine
      uses: actions/checkout@v4
      with:
        repository: DiligentGraphics/DiligentEngine
        path:       ${{github.workspace}}/DiligentEngine
        submodules: true
        ref: development

    - name: Install Doxygen
      shell: bash
      run: |
        DOXYGEN_VERSION=1.13.2
        wget https://doxygen.nl/files/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
        tar -xzf doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
        sudo cp -r doxygen-$DOXYGEN_VERSION/bin/* /usr/local/bin/
        rm -rf doxygen-$DOXYGEN_VERSION*
        doxygen --version

    - name: Build Documentation
      working-directory: ${{github.workspace}}/DiligentEngine
      shell: bash
      run: |
        # Build page structure
        python Doc/md_pages.py Doc/pages.dox
        # Build documentation
        mkdir -p build/docs
        doxygen Doc/doxygen.cfg