name: Windows

on: [push, pull_request]

jobs:
  build-win10:
    strategy:
      matrix:
        toolset: [x64, Win32]
        config: [Debug]
        include:
          - toolset: Win32
            cmake_generator: "Ninja"
          - toolset: x64
            cmake_generator: "Visual Studio 16 2019"

    runs-on: windows-2019
    name: Win10 -> ${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTests
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Ninja
      if: ${{ matrix.cmake_generator == 'Ninja' }}
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup Developer Command Prompt for VS
      if: ${{ matrix.cmake_generator == 'Ninja' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.toolset }}

    - name: Configure CMake
      if: success()
      env:
        CMAKE_GENERATOR: ${{ matrix.cmake_generator }}
        #CMAKE_GENERATOR_PLATFORM: ${{ matrix.toolset }}
      shell: bash
      run: |
        #cd $GITHUB_WORKSPACE/DiligentTests/BuildTools/Scripts/github_actions
        #./create_cmake.sh "$GITHUB_WORKSPACE"
        #cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        #./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }}
        cd "${{runner.workspace}}"
        mkdir build
        cd ./build
        cmake "$GITHUB_WORKSPACE" -DCMAKE_BUILD_TYPE=${{runner.config}}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }}

    - name: Tests
      if: success()
      shell: bash
      run: |
        #cd "${{runner.workspace}}\DiligentTests\Tests\DiligentToolsTest\assets"
        export BIN_DIR="${{runner.workspace}}\build\DiligentCoreTests"
        if [ "${{ matrix.cmake_generator }}" != "Ninja" ]; then BIN_DIR="$BIN_DIR\${{ matrix.config }}"; fi
        "$BIN_DIR\DiligentCore_Tests.exe"


  codespell-linux:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug]

    runs-on: ubuntu-latest
    name: Linux -> codespell

    steps:
    - name: Clone DiligentTests
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore

    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        #ignore_words_file: .github/codespellignore
        ignore_words_list: ser,inout,lod,pres,boundimg,ot
        skip: DiligentCore/ThirdParty,ThirdParty
        path: .
