name: Windows

on: [push, pull_request]

jobs:
  build-win10:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug]

    runs-on: windows-2019
    name: Win10 -> ${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTests
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        #cd $GITHUB_WORKSPACE/DiligentTests/BuildTools/Scripts/github_actions
        #./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }}

    - name: Tests
      if: success()
      shell: bash
      run: |
        #cd "${{runner.workspace}}\DiligentTests\Tests\DiligentToolsTest\assets"
        "${{runner.workspace}}\build\DiligentCoreTests\${{ matrix.config }}\DiligentCore_Tests.exe"
